---
- name: Main yml
  hosts: all 
  become: true
  tasks:

  - name: update repository index
    apt: 
      update_cache: yes
    when: ansible_distribution in [ "Debian GNU/Linux", "Ubuntu" ] 

  - name: install apache2 package on Debian
    apt: 
      name: apache2
      state: latest
    when: ansible_distribution == "Debian GNU/Linux"
