# -*- mode: ruby -*-
# vi: set ft=ruby :

# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.
BOX_IMAGE = "ubuntu/trusty64"
NODE_COUNT = 3
NODE_COUNT2 = 2

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "master"
    subconfig.vm.network :private_network, ip: "10.0.0.10"
  end

  # Provision Ubuntu servers  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
     subconfig.vm.box = BOX_IMAGE
     subconfig.vm.hostname = "node#{i}"
     subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
    end
  end

  # Provision debian servers
  (4..5).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = "generic/debian9"
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
    end
  end

  # Install avahi on all machines  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y avahi-daemon libnss-mdns
  SHELL
end