# -*- mode: ruby -*-
# vi: set ft=ruby :

# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.
BOX_IMAGE = "ubuntu/trusty64"
NODE_COUNT = 3
NODE_COUNT2 = 2

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = "master"
    subconfig.vm.hostname = "master"
    subconfig.vm.network :private_network, ip: "10.0.0.10"
  end

  # Provision Ubuntu servers  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
     subconfig.vm.box = "node#{i}"
     subconfig.vm.hostname = "node#{i}"
     subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
    end
  end

  # Provision debian servers
  (4..5).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = "node#{i}"
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
    end
  end

     # ...
    #config.vm.box = 'filename'
    #config.vm.box_url = 'http://your-url.com/filename.box'

  # Increase memory and cpus
  config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      #config.vm.synced_folder ".", "/vagrant", type: "nfs"
  end

end
